#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$ROOT_DIR/.env"
FORCE=0
DRY_RUN=0

usage() {
  cat <<'USAGE'
Usage: scripts/vdoc-local-bootstrap.sh [--output PATH] [--force] [--dry-run]

Generate a local-only Docker Compose .env with disposable credentials.
Secrets are written only to the output file and are never printed.
USAGE
}

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output)
      [[ $# -ge 2 ]] || die "--output requires a path"
      OUTPUT="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return
  fi
  od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
}

repository_provenance() {
  local repo_dir="$1"
  local commit version build_time status
  [[ -d "$repo_dir" ]] || die "Missing repository for build provenance: $repo_dir"
  commit="$(git -C "$repo_dir" rev-parse HEAD 2>/dev/null)" || die "Cannot read Git commit for build provenance: $repo_dir"
  [[ "$commit" =~ ^[0-9a-f]{40}$ ]] || die "Invalid Git commit for build provenance: $repo_dir"
  version="$(git -C "$repo_dir" describe --tags --always HEAD 2>/dev/null)" || die "Cannot derive version for build provenance: $repo_dir"
  build_time="$(git -C "$repo_dir" show -s --format=%cI HEAD 2>/dev/null)" || die "Cannot derive build time for build provenance: $repo_dir"
  status="$(git -C "$repo_dir" status --porcelain=v1 --untracked-files=all)"
  if [[ -n "$status" ]]; then
    version="${version}-dirty"
    commit="${commit}-dirty"
    build_time="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  fi
  printf '%s\t%s\t%s\n' "$version" "$commit" "$build_time"
}

render_env() {
  local postgres_password storage_access_key storage_secret_key jwt_key mcp_key
  local backend_version backend_commit backend_build_time
  local admin_version admin_commit admin_build_time
  postgres_password="$(random_hex)"
  storage_access_key="$(random_hex)"
  storage_secret_key="$(random_hex)"
  jwt_key="$(random_hex)"
  mcp_key="$(random_hex)"
  IFS=$'\t' read -r backend_version backend_commit backend_build_time < <(repository_provenance "$ROOT_DIR/Vdoc")
  IFS=$'\t' read -r admin_version admin_commit admin_build_time < <(repository_provenance "$ROOT_DIR/Vdoc-admin")

  cat <<ENV
# Generated by scripts/vdoc-local-bootstrap.sh for disposable local Compose use.
# Do not commit this file. Rotate these values if they leave your machine.
VDOC_PUBLISH_ADDRESS=127.0.0.1
VDOC_POSTGRES_HOST_PORT=5432
VDOC_RUSTFS_HOST_PORT=9000
VDOC_RUSTFS_CONSOLE_HOST_PORT=9001
VDOC_BACKEND_HOST_PORT=8080
VDOC_ADMIN_HOST_PORT=8081
VDOC_BACKEND_CONTAINER_PORT=8080
VDOC_BACKEND_VERSION=$backend_version
VDOC_BACKEND_GIT_COMMIT=$backend_commit
VDOC_BACKEND_BUILD_TIME=$backend_build_time
VDOC_ADMIN_VERSION=$admin_version
VDOC_ADMIN_GIT_COMMIT=$admin_commit
VDOC_ADMIN_BUILD_TIME=$admin_build_time
VDOC_BACKEND_PUBLIC_ORIGIN=http://127.0.0.1:8080
VDOC_ADMIN_API_BASE_URL=http://127.0.0.1:8080
VDOC_SERVER_CORS_ALLOWED_ORIGINS=http://127.0.0.1:8081,http://localhost:8081
VDOC_AUTH_ALLOW_REGISTRATION=true
VDOC_AUTH_RATE_LIMIT=2
VDOC_AUTH_RATE_BURST=5
VDOC_POSTGRES_DB=vdoc
VDOC_POSTGRES_USER=vdoc
VDOC_POSTGRES_PASSWORD=$postgres_password
VDOC_TEST_POSTGRES_DB=vdoc_e2e
VDOC_STORAGE_BUCKET=vdoc
VDOC_STORAGE_ACCESS_KEY=$storage_access_key
VDOC_STORAGE_SECRET_KEY=$storage_secret_key
VDOC_JWT_KEY=$jwt_key
VDOC_MCP_TOKEN_CIPHER_KEY=$mcp_key
VDOC_MCP_TOKEN_CIPHER_KID=local-aes-gcm-v1
VDOC_MCP_TOKEN_CIPHER_KEYRING={}
VDOC_INITIAL_ADMIN_EMAIL=
VDOC_INITIAL_ADMIN_NAME=
VDOC_INITIAL_ADMIN_PASSWORD=
TZ=Asia/Shanghai
VDOC_RUSTFS_CORS_ALLOWED_ORIGINS=http://127.0.0.1:9001,http://localhost:9001
VDOC_RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=http://127.0.0.1:9001,http://localhost:9001
VDOC_RUSTFS_LOG_LEVEL=info
ENV
}

if [[ -e "$OUTPUT" && "$FORCE" -ne 1 ]]; then
  die "Refusing to overwrite $OUTPUT without --force"
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  printf 'Dry run: would write local Compose env to %s\n' "$OUTPUT"
  printf 'Generated secret values are not printed; use without --dry-run to create the file.\n'
  exit 0
fi

mkdir -p "$(dirname -- "$OUTPUT")"
tmp="$(mktemp "${OUTPUT}.tmp.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
umask 077
render_env >"$tmp"
mv "$tmp" "$OUTPUT"
trap - EXIT
printf 'Wrote local Compose env to %s\n' "$OUTPUT"
printf 'Next: docker compose --env-file %s config --quiet\n' "$OUTPUT"
